apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
  labels:
    app: my-app
data:
  file: |
    This is a value from ConfigMap
    Accessible via /conf/file
  
  nginx.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        location /conf/ {
            alias /homework/conf/;
            default_type text/plain;
            autoindex off;
            try_files $uri =404;
        }
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }